CREATE TABLE `USER` (
    `ID` VARCHAR(36) NOT NULL,
    `NAME` VARCHAR(100) NOT NULL,
    `ACTIVE` BIT NOT NULL,
    `TENANT_ID` VARCHAR(36) NOT NULL,
    `CREATED_DATE`  DATETIME NOT NULL,
    `UPDATED_DATE` DATETIME NULL
) ENGINE=InnoDB DEFAULT CHARSET=UTF8MB4;