CREATE TABLE `USER` (
    `ID` VARCHAR(36) NOT NULL,
    `USERNAME` VARCHAR(100) NOT NULL,
    `PASSWORD` VARCHAR(100) NOT NULL,
    `TENANT_ID` VARCHAR(36) NOT NULL,
    `NAME` VARCHAR(100) NOT NULL,
    `ACTIVE` BOOLEAN NOT NULL,
    `CREATED_DATE`  DATETIME NOT NULL,
    `UPDATED_DATE` DATETIME NULL,
    `ROLE` VARCHAR(50) NOT NULL,
    PRIMARY KEY (`ID`),
    CONSTRAINT `FK_USER_TENANT` FOREIGN KEY (`TENANT_ID`) REFERENCES `TENANT` (`ID`),
    INDEX `IDX_USER_USERNAME` (`USERNAME`)
) ENGINE=InnoDB DEFAULT CHARSET=UTF8MB4;