CREATE TABLE `TENANT` (
    `ID` VARCHAR(36) NOT NULL,
    `NAME` VARCHAR(100) NOT NULL,
    `ACTIVE` BIT NOT NULL,
    `CREATED_DATE`  DATETIME NOT NULL,
    `UPDATED_DATE` DATETIME NULL,
    PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=UTF8MB4;
INSERT INTO `TENANT` (ID, NAME, ACTIVE, CREATED_DATE) VALUES ('1', 'Default', TRUE, now());