CREATE TABLE `TENANT` (
    `ID` VARCHAR(36) NOT NULL,
    `NAME` VARCHAR(100) NOT NULL,
    `ACTIVE` BOOLEAN NOT NULL,
    `CREATED_DATE`  DATETIME NOT NULL,
    `UPDATED_DATE` DATETIME NULL,
    PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=UTF8MB4;