CREATE TABLE `USER` (
    `ID` VARCHAR(36) NOT NULL,
    `TENANT_ID` VARCHAR(36) NOT NULL,
    `NAME` VARCHAR(100) NOT NULL,
    `ACTIVE` BIT NOT NULL,
    `CREATED_DATE`  DATETIME NOT NULL,
    `UPDATED_DATE` DATETIME NULL,
    PRIMARY KEY (`ID`),
    CONSTRAINT `FK_USER_TENANT` FOREIGN KEY (`TENANT_ID`) REFERENCES `TENANT` (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=UTF8MB4;